// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBfcIotyi_v3QqtC0o-PyMXikmMW-2Sow',
    appId: '1:258205121309:web:0db3310c474003b16f3ff4',
    messagingSenderId: '258205121309',
    projectId: 'data-storage-1ef35',
    authDomain: 'data-storage-1ef35.firebaseapp.com',
    storageBucket: 'data-storage-1ef35.appspot.com',
    measurementId: 'G-GYQTTEG7W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBywX17LsVVONR7EpezO24QwFzsVuUydDU',
    appId: '1:258205121309:android:5297688b2ce36d146f3ff4',
    messagingSenderId: '258205121309',
    projectId: 'data-storage-1ef35',
    storageBucket: 'data-storage-1ef35.appspot.com',
  );
}
